---
:shared:
  :versions:
  - id
  - created_at
  - event
  - item_id
  - item_type
  - note
  - object
  - object_changes
  - whodunnit
  :delayed_jobs:
  - id
  - attempts
  - created_at
  - cron
  - failed_at
  - handler
  - last_error
  - locked_at
  - locked_by
  - priority
  - queue
  - run_at
  - updated_at
  :sessions:
  - id
  - created_at
  - data
  - session_id
  - updated_at
  :active_storage_variant_records:
  - id
  - blob_id
  - variation_digest
  :active_storage_blobs:
  - id
  - byte_size
  - checksum
  - content_type
  - created_at
  - filename
  - key
  - metadata
  - service_name
  :active_storage_attachments:
  - id
  - blob_id
  - created_at
  - name
  - record_id
  - record_type
  :get_an_identity_webhook_messages:
  - id
  - created_at
  - message
  - message_id
  - message_type
  - processed_at
  - raw
  - sent_at
  - status
  - status_comment
  - updated_at
  :statements:
  - reconcile_amount
  :legacy_passed_participant_outcomes:
  - id
  - completion_date
  - course_short_code
  - created_at
  - trn
  - updated_at
  :financial_change_logs:
  - id
  - created_at
  - data_changes
  - operation_description
  - updated_at
  :course_cohort_providers:
  - id
  - course_cohort_id
  - created_at
  - lead_provider_id
  - updated_at
  :course_cohorts:
  - id
  - cohort_id
  - course_id
  - created_at
  - ecf_id
  - schedule_id
  - updated_at
  :courses:
  - position
  :contract_templates:
  - id
  - created_at
  - ecf_id
  - monthly_service_fee
  - number_of_payment_periods
  - output_payment_percentage
  - per_participant
  - recruitment_target
  - service_fee_installments
  - service_fee_percentage
  - special_course
  - targeted_delivery_funding_per_participant
  - updated_at
  :contracts:
  - id
  - contract_template_id
  - course_id
  - created_at
  - statement_id
  - updated_at
  :closed_registration_users:
  - id
  - created_at
  - email
  - updated_at
  :application_lead_providers:
  - id
  - application_id
  - created_at
  - current
  - lead_provider_id
  - updated_at
  :application_events:
  - type
  :api_tokens:
  - id
  - created_at
  - hashed_token
  - last_used_at
  - lead_provider_id
  - scope
  - updated_at
  :admin_users:
  - id
  - created_at
  - email
  - full_name
  - otp_expires_at
  - otp_hash
  - super_admin
  - updated_at
  :adjustments:
  - id
  - amount
  - created_at
  - description
  - statement_id
  - updated_at
  :applications:
  - raw_application_data
  :users:
  - archived_email
  - date_of_birth
  - national_insurance_number
  - raw_tra_provider_data
  - refresh_token
  - refresh_token_updated_at
  :bulk_operations:
  - id
  - admin_id
  - created_at
  - finished_at
  - ran_by_admin_id
  - result
  - row_count
  - started_at
  - type
  - updated_at
  :flipper_gates:
  - id
  - created_at
  - feature_key
  - key
  - updated_at
  - value
  :flipper_features:
  - id
  - created_at
  - key
  - updated_at
