---
shared:
  :statements:
    - id
    - academic_year
    - deadline_date
    - payment_date
    - output_fee
    - start_date
    - frequency
    - lead_provider_id
    - marked_as_paid_at
    - state
    - created_at
    - updated_at
    - ecf_id
  :schools:
    - id
    - close_date
    - ukprn
    - last_changed_date
    - created_at
    - updated_at
    - high_pupil_premium
    - eyl_funding_eligible
    - la_code
    - la_name
    - establishment_status_code
    - establishment_status_name
    - establishment_type_code
    - establishment_type_name
    - phase_type
    - phase_name
    - number_of_pupils
  :schedules:
    - id
    - cohort_id
    - name
    - identifier
    - training_starts_at
    - training_ends_at
    - allowed_declaration_types
    - created_at
    - updated_at
    - ecf_id
    - policy_descriptor
    - acceptance_window_start
    - acceptance_window_end
    - course_group
  :registration_interests:
    - id
    - email
    - notified
    - created_at
    - updated_at
  :private_childcare_providers:
    - id
    - local_authority
    - early_years_individual_registers
    - provider_early_years_register_flag
    - provider_compulsory_childcare_register_flag
    - created_at
    - updated_at
    - disabled_at
  :participant_outcomes:
    - id
    - state
    - completion_date
    - declaration_id
    - created_at
    - updated_at
    - ecf_id
  :participant_id_changes:
    - id
    - user_id
    - created_at
    - updated_at
    - ecf_id
    - from_participant_id
    - to_participant_id
  :local_authorities:
    - id
    - high_pupil_premium
    - created_at
    - updated_at
  :institutions:
    - id
    - institutionable_type
    - institutionable_id
    - name
    - address_1
    - address_2
    - address_3
    - town
    - county
    - postcode
    - postcode_without_spaces
    - region
    - institution_reference_number
    - created_at
    - updated_at
  :lead_providers:
    - id
    - name
    - created_at
    - updated_at
    - ecf_id
    - hint
    - url
  :delivery_partners:
    - id
    - ecf_id
    - name
    - created_at
    - updated_at
  :delivery_partnerships:
    - id
    - delivery_partner_id
    - lead_provider_id
    - course_cohort_id
    - created_at
    - updated_at
  :declarations:
    - id
    - ecf_id
    - statement_id
    - type
    - application_id
    - superseded_by_id
    - lead_provider_id
    - cohort_id
    - declaration_type
    - declaration_date
    - state
    - state_reason
    - created_at
    - updated_at
    - delivery_partner_id
    - secondary_delivery_partner_id
    - milestone_id
    - paid_declaration_id
    - clawback_declaration_id
  :courses:
    - id
    - name
    - created_at
    - updated_at
    - ecf_id
    - description
    - display
    - identifier
    - course_group
    - short_code
    - position
  :course_cohorts:
    - id
    - academic_year
    - cohort_id
    - course_id
    - created_at
    - ecf_id
    - schedule_id
    - updated_at
  :course_cohort_providers:
    - id
    - course_cohort_id
    - created_at
    - lead_provider_id
    - updated_at
  :cohorts:
    - id
    - start_year
    - registration_starts_at
    - registration_ends_at
    - created_at
    - updated_at
    - funding_cap
    - ecf_id
    - identifier
    - description
  :application_events:
    - id
    - type
    - application_id
    - lead_provider_id
    - event
    - metadata
    - created_at
    - updated_at
  :application_lead_providers:
    - id
    - application_id
    - lead_provider_id
    - current
    - assigned_at
    - unassigned_at
  :applications:
    - id
    - user_id
    - course_cohort_id
    - created_at
    - updated_at
    - ecf_id
    - eligible_for_funding
    - funding_choice
    - ukprn
    - teacher_catchment
    - teacher_catchment_country
    - works_in_school
    - works_in_nursery
    - works_in_childcare
    - kind_of_nursery
    - funding_eligiblity_status_code
    - work_setting
    - primary_establishment
    - number_of_pupils
    - status
    - participant_outcome_state
    - institution_id
    - teacher_catchment_iso_country_code
    - targeted_support_funding_eligibility
    - notes
    - funded_place
    - referred_by_return_to_teaching_adviser
    - on_submission_trn
    - review_status
  :users:
    - id
    - created_at
    - updated_at
    - ecf_id
    - trn
    - email
    - full_name
    - active_alert
    - feature_flag_id
    - provider
    - updated_from_tra_at
    - trn_lookup_status
    - notify_user_for_future_reg
    - email_updates_status
    - email_updates_unsubscribe_key
    - archived_at
    - significantly_updated_at
    - preferred_name
  :eligibility_list_entries:
    - id
    - type
    - identifier
    - identifier_type
    - created_at
    - updated_at
  :milestones:
    - id
    - declaration_type
    - created_at
    - updated_at
    - course_cohort_id
    - acceptance_window_start_date
    - acceptance_window_end_date
    - payment_amount
